### ISSUE TITLE
PRの本文内にシングルクォーテーション（'）が存在するとエラーになります。

### ISSUE THREAD

**Issue by kotaueda** [pj8/github-backlog-sync#15]
本文の通りになります。

**Comment by yuki777** [comment]
エラーはこちら
https://github.com/pj8/Hpplus.Spur/actions/runs/11290060449/job/31401114748

**Comment by yuki777** [comment]
@kotaueda 
- #19 で解決しました!

**Comment by yuki777** [comment]
document: https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
